IMPORT LIBRARIES AND DATA EXPLORATION

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.model_selection as model_selection
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (mean_absolute_error,mean_squared_error,r2_score)

In [ ]:
from google.colab import files

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving T2-Superstore.csv to T2-Superstore (8).csv

In [ ]:
df = pd.read_csv('T2-Superstore.csv', encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [ ]:
print(f"Number of Rows    : {df.shape[0]}")
print(f"Number of Columns : {df.shape[1]}")

Number of Rows    : 9994
Number of Columns : 21

In [ ]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [ ]:
print(df.dtypes)

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [ ]:
df.shape

(9994, 21)

In [ ]:
print(df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.strip()
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

DATA CLEANING

DATA CLEANING & DATA PREPROCESSING

In [ ]:
df_copy=df.copy()
strange_values =['_','-','.','nan','NAN','na','null','NA','NULL','unknown','UNKNOWN']

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9989    False
9990    False
9991    False
9992    False
9993    False
Length: 9994, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.duplicated().drop_duplicates()

0    False
dtype: bool

In [ ]:
df.isnull()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9990,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9991,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9992,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9993,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Feature Engineering & Selection

In [ ]:
df['Order Date']=pd.to_datetime(df['Order Date'])

In [ ]:
df['Year'] = df['Order Date'].dt.year

In [ ]:
df['Month'] = df['Order Date'].dt.month

In [ ]:
df['Day'] = df['Order Date'].dt.day

In [ ]:
df['Quater'] = df['Order Date'].dt.quarter

In [ ]:
df['Day Of Week'] = df['Order Date'].dt.day_name()

DATA ENCODING

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
df.select_dtypes(include='object').columns

Index(['Order ID', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name',
       'Segment', 'Country', 'City', 'State', 'Region', 'Product ID',
       'Category', 'Sub-Category', 'Product Name', 'Day Of Week'],
      dtype='object')

In [ ]:
label_encoder=LabelEncoder()
bin_cols=['Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region',
       'Product ID', 'Category', 'Sub-Category', 'Product Name']

In [ ]:
for col in bin_cols:
  df[col] = df[col].astype(str)
  df[col]=label_encoder.fit_transform(df[col])

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Day,Quater,Day Of Week
0,1,CA-2016-152156,2016-11-08,219,2,143,166,0,0,194,...,386,261.9600,2,0.00,41.9136,2016,11,8,4,Tuesday
1,2,CA-2016-152156,2016-11-08,219,2,143,166,0,0,194,...,839,731.9400,3,0.00,219.5820,2016,11,8,4,Tuesday
2,3,CA-2016-138688,2016-06-12,906,2,237,201,1,0,266,...,1433,14.6200,2,0.00,6.8714,2016,6,12,2,Sunday
3,4,US-2015-108966,2015-10-11,128,3,705,687,0,0,153,...,366,957.5775,5,0.45,-383.0310,2015,10,11,4,Sunday
4,5,US-2015-108966,2015-10-11,128,3,705,687,0,0,153,...,573,22.3680,2,0.20,2.5164,2015,10,11,4,Sunday

In [ ]:
df.drop(['Order Date'],axis=1,inplace=True)

In [ ]:
df.to_excel("Data set.csv.xlsx",index=False)

X AND Y JUSTIFICATION

In [ ]:
y=df['Sales']
x=df.drop(['Sales', 'Order ID', 'Day Of Week'],axis=1)

VISUALISATION

In [ ]:
monthlysales=df.groupby('Month')['Sales'].sum()

In [ ]:
regionwise_sales=df.groupby('Region')['Sales'].sum()

In [ ]:
category_sales=df.groupby('Category')['Sales'].sum()

MULTI LINEAR REGRESSION

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
model.score(x_train, y_train)

0.44242945424036717

In [ ]:
model

LinearRegression()

In [ ]:
model.coef_

array([ 2.14772864e-04, -6.51796698e-03,  1.27295947e+00,  7.28310392e-02,
       -5.40120416e-02, -3.55797287e+00,  3.32267547e-12,  6.51304425e-02,
        4.82750395e-01, -2.03801964e-04,  5.47123443e+00, -2.32205751e-01,
        1.69520911e+02,  2.04823165e+01, -3.10041521e-02,  4.19338086e+01,
        2.79119520e+02,  1.57321241e+00, -2.74943910e+00, -1.59915119e-02,
        4.20982756e-01,  3.36147933e+00])

In [ ]:
model.intercept_

np.float64(5387.114606599763)

DATA EVALUTION

In [ ]:
predict=model.predict(x_test)
predict

array([246.05235009, 111.74356345, 152.78977874, ..., 241.43955803,
       317.25634356, -15.13391108])

In [ ]:
result=pd.DataFrame({'Actual':y_test,'Predicted':predict})
result

       Actual   Predicted
3125  563.808  246.052350
1441   36.672  111.743563
4510   37.300  152.789779
39    212.058  132.886506
4509  171.288  281.641983
...       ...         ...
9956   46.350  258.919662
1561    2.780  -29.661222
1670   16.680  241.439558
6951  479.988  317.256344
3910  352.450  -15.133911

[1999 rows x 2 columns]

In [ ]:
mse=mean_squared_error(y_test,predict)
mse

671072.0091125277

In [ ]:
mean_absolute_error(y_test,predict)

244.91071911585817

In [ ]:
rmse=np.sqrt(mse)
rmse

np.float64(819.1898492489563)

In [ ]:
r2_score=r2_score(y_test,predict)
r2_score

-0.13606392452774307

Logistic Regresssion Model

In [ ]:
#DISPLAY CATOGORICAL COLUMS
ctg_cols = df.select_dtypes(include="object").columns
print(ctg_cols)

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region',
       'Product ID', 'Category', 'Sub-Category', 'Product Name'],
      dtype='object')

In [ ]:
df = df.drop("customerID", axis=1)

KeyError: "['customerID'] not found in axis"